variables:
  # NOTE: The build requires NETLIFY_AUTH_TOKEN
  # and NETLIFY_SITE_ID variables, too
  ZOLA_VERSION: "0.6.0"
  PDF_SERVER: "true"
  DEPLOY_PRIME_URL: "http://127.0.0.1:7878"

stages:
  - test
  - deploy

test:
  image: node:latest
  script:
    - bash scripts/build.sh
  artifacts:
    paths:
      - public/
  except:
    - master

deploy:
  image: node:latest
  script:
    - bash scripts/build.sh
    - npm run deploy -- --prod
  artifacts:
    paths:
      - public/
  only:
    - master
