name: Build

on:
  push:
    branches: [main]
  pull_request:
    types: [ready_for_review, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    steps:
      - name: Install OS dependencies
        run: sudo apt-get install -qy curl jq
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "16"
      - name: Install Dependencies
        run: ./scripts/setup.sh
      - name: Build
        run: ./scripts/build.sh
        env:
          DEPLOY_PRIME_URL: https://resume.secretfader.com
      - name: Store Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: public/
